### PR TITLE
Vc12 support + OpenCV 2.4.9

### PR DESCRIPTION
**Pull request by brucelane**
support for vs2013 added
updated to OpenCV 2.49, Windows OS only

### CODE REVIEW

**Comment by richardeakin** [comment]
Thanks for this.  Although we'd like to not add unnecessary binary cruft where possible, since it will be dragged along with every commit checkout.  Can you make a new pull request that only contains updated binaries for 2.4.9?

Also, is this tested?

**Comment by richardeakin** [comment]
While here, can you also past a copy of the build commands you used to create the binaries?

**Comment by brucelane** [comment]
It's only tested successful for one hour...
Needs more tests from other people using more features than I use (I only use it in the context of the warping block).
These libs were downloaded from the official http://opencv.org/ website, I didn't have to recompile.
I add the binaries now

**Comment by andrewfb** [comment]
Thanks for this - binaries are updated for both vc2012 and vc2013 x86. I am leaving x86_64 out for its size weighed relative to how many users are using 64-bit on MSW. These binaries are actually from the official OpenCV distribution.

**Pull request closed without merging**
